<?php

namespace LoneWolfAppBundle\Repository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInOrder()
    {
        $qb = $this->createQueryBuilder('e');
        return $qb->orderBy('e.position', 'ASC')
            ->getQuery()
            ->execute()
            ;
    }
}
